name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvmrc.outputs.node_version }}'
      - run: npm ci
      - run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
          CLEAN: true